[project]
name = "upstaget-week3-day5-daily"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "mysql-connector-python>=9.5.0",
    "uvicorn>=0.40.0",
]
